name: Build on Push

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@v3

    - name: Configure CMake
      run: cmake -S . -B build # -DSFML_BUILD_STATIC_LIBS=ON

    - name: Build project
      run: cmake --build . # build --config Release
