name: Build on Push

on:
  push:
    branches:
      - dev  # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]] #, windows-latest]  # Test on all platforms

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install X11 Dependencies
      run: sudo apt-get update && sudo apt-get install -y libx11-dev libxrandr-dev libxcursor-dev libxi-dev
      
    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake --trace -S . -B build

    - name: Build project
      run: cmake --build . # build --config Release
