name: Build on Push

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Test on all platforms

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -S . -B build # -DSFML_BUILD_STATIC_LIBS=ON

    - name: Build project
      run: cmake --build . # build --config Release
      
branding:
  icon: 'terminal'  
  color: 'green'
